dist:  xenial
language:  python
python:  3.7.2

services:
  - docker

branches:
  only:
  - master
  - testing
  - /^ci-.*$/

env:
  - APP_DIR="$TRAVIS_BUILD_DIR/loansapp"
    DOCKER_APP_DIR="$TRAVIS_BUILD_DIR/dockerloansapp"

before_install:
  - echo -e "Default Environment Variables:\n------------------------\n
    TRAVIS_BUILD_DIR='$TRAVIS_BUILD_DIR'\n\n
    Custom Environment Variables\n------------------------\n
    APP_DIR='$APP_DIR'\nDOCKER_APP_DIR='$DOCKER_APP_DIR'"
  - ls -al $TRAVIS_BUILD_DIR
  - pip install pipenv

install:
  - cd $APP_DIR && pipenv lock && cd $TRAVIS_BUILD_DIR

before_script:
  - if [ -f $DOCKER_APP_DIR/.env ]; then cp dockerloansapp/.env $DOCKER_APP_DIR/.env;\
    else echo "No .env file found. Create a .env file containing the TEST DATABASE credentials"; exit 1; fi
  - if [ -f $DOCKER_APP_DIR/.env.override ]; then rm $DOCKER_APP_DIR/.env.override; fi
  # set RUN_MODE for testdb connection and prevent pytest from creating binary __pycache__ files
  - echo -e "RUN_MODE=TEST\nPYTHONDONTWRITEBYTECODE=1" > $DOCKER_APP_DIR/.env.override
  - ls -al $DOCKER_APP_DIR

script:
  - cd $DOCKER_APP_DIR && docker-compose up -d --build
  - docker-compose exec web sh -c 'if [ -z ${RUN_MODE+TEST} ]; then echo "RUN_MODE is unset"; \
    else echo "RUN_MODE is set to ..."; fi && set | grep RUN_MODE'
  - docker-compose exec web sh -c 'pytest -v --disable-warnings'

