dist:  xenial
language:  python
python:  3.7.2

services:
  - docker

branches:
  only:
  - master
  - /^ci-.*$/

env:
  - APP_DIR="$TRAVIS_BUILD_DIR/loansapp"
  - echo -e "Default Environment Variables:\n------------------------\n
    TRAVIS_BUILD_DIR='$TRAVIS_BUILD_DIR'\n\n
    Custom Environment Variables\n------------------------\n
    APP_DIR='$APP_DIR'"
  - ls -al $TRAVIS_BUILD_DIR

install:
  - ls -al $APP_DIR
  - cd $APP_DIR && pipenv lock && cd $TRAVIS_BUILD_DIR

script:
  - cd $APP_DIR && docker-compose -f docker-compose.testing.yml up -d --build
  - docker ps -a
  - docker-compose exec web sh -c 'pytest -v --disable-warnings'
