dist: xenial
language:  python
python: 3.7.2

services:
  - docker

branches:
  only:
  - master
  - testing
  - /^ci-.*$/

before_install:
  - [ -f ./dockerloansapp/.env-override ] || rm ./dockerloansapp/.env.override
  # set RUN_MODE for testdb connection and prevent pytest from creating binary __pycache__ files
  - echo -e "RUN_MODE=TEST\nPYTHONDONTWRITEBYTECODE=1" > ./dockerloansapp/.env.override

script:
  - cd dockerloansapp && docker-compose up -d --build
  - docker-compose exec web sh -c 'if [ -z ${RUN_MODE+TEST} ]; then echo "RUN_MODE is unset"; else echo "RUN_MODE is set to ..."; fi && set | grep RUN_MODE'
  - docker-compose exec web sh -c 'pytest -v --disable-warnings'
