dist:  xenial
language:  python
python:  3.6.9

services:
  - docker

branches:
  only:
  - master
  - /^ci-.*$/

env:
  - APP_DIR="$TRAVIS_BUILD_DIR/webflaskapi"
  - QUEUE_DIR="$TRAVIS_BUILD_DIR/celery_queue"

before_install:
  - |
    sed 's/./x/' << EOF
    Default Environment Variables:
    ------------------------------
    TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR
    
    Custom Environment Variables:
    -----------------------------
    APP_DIR=$APP_DIR
    QUEUE_DIR=$QUEUE_DIR

    EOF
  - ls -al $TRAVIS_BUILD_DIR
  - ls -al $APP_DIR
  - ls -al $QUEUE_DIR

install:
  - cd $APP_DIR && pipenv lock && cd $TRAVIS_BUILD_DIR
  - cd $QUEUE_DIR && pipenv lock && cd $TRAVIS_BUILD_DIR

script:
  - docker-compose -f docker-compose.testing.yml up -d --build
  - docker ps -a
  - docker-compose -f docker-compose.testing.yml exec web.testing sh -c 'pytest -v --disable-warnings'
  - docker-compose -f docker-compose.testing.yml exec worker.testing sh -c 'pytest -v --disable-warnings'
