version: '3'
services:
  web:
    build: ./loansapp
    env_file:
      - .env.development.yml
    volumes:
      - ./loansapp:/app
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=loansapi/api.py
      - FLASK_DEBUG=1
      - RUN_MODE=DEVELOPMENT
      - 'RUN=pipenv run flask run --host=0.0.0.0 --port=5000'
    # Infinite loop, to keep it alive, recommended for debugging
    # Comment out for running directly on uswgi/nginx
    command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
  postgres:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgres/data
    environment:
      POSTGRES_DB: "${DEV_DB}"
      POSTGRES_USER: "${DEV_USER}"
      POSTGRES_PASSWORD: "${DEV_PASSWORD}"
    networks:
      - default
  pgadmin:
    image:  dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - default
volumes:
    postgresdata:
