version: '3'
services:
  web.flaskapi:
    build: ./loansapp
    env_file:
      - .env.web.dev
    volumes:
      - ./loansapp:/app
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=loansapi/api.py
      - FLASK_DEBUG=1
      - RUN_MODE=DEVELOPMENT
      - C_FORCE_ROOT=true
      - 'RUN=pipenv run flask run --host=0.0.0.0 --port=5000'
    # Infinite loop, to keep it alive, recommended for debugging
    # Comment out for running directly on uswgi/nginx
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
    depends_on:
      - postgres.flaskapi
      - redis.flaskapi
    networks:
      - default
  postgres.flaskapi:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_flaskapi_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: "${DEV_DB}"
      POSTGRES_USER: "${DEV_USER}"
      POSTGRES_PASSWORD: "${DEV_PASSWORD}"
    networks:
      - default
  worker.flaskapi:
    build: ./celery
    env_file:
      - .env.worker.dev
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - redis.flaskapi
    networks:
      - default
  flower.flaskapi:
    build: ./celery
    ports:
      - "5555:5555"
    entrypoint: flower
    command: ["-A", "tasks", "--port=5555", "--broker=${REDIS_URI}"]
    depends_on:
      - redis.flaskapi
  redis.flaskapi:
    image: redis:5.0-alpine
    environment:
      REDIS_PASSWD: "${REDIS_PASSWD}"
    volumes:
      - redis_flaskapi_data:/data
    command: redis-server --requirepass "${REDIS_PASSWD}"
    ports:
      - '6379:6379'
    networks:
      - default
  pgadmin:
    image:  dpage/pgadmin4
    depends_on:
      - postgres.flaskapi
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - default
volumes:
    postgres_flaskapi_data:
    redis_flaskapi_data:
