version: '3'
services:
  web:
    build: ./app
  postgres:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgres/data
    environment:
      POSTGRES_DB: flask_api
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flaskdb
    networks:
      - default
  testdb:
    image: postgres:11.2
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: test_api
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    networks:
      - default
  pgadmin:
    image:  dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - default
volumes:
    postgresdata:
